language: go

go_import_path: github.com/mhtshhp/multitask

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

matrix:
  fast_finish: true
  include:
    - go: 1.12.x
      env: GO111MODULE=on
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.15.x
    - go: master

script:
  - go build -v ./...
  - go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
